PUT http://localhost:3000/user/roaa223359@bue.edu.eg
Content-Type: application/json


{
    "fname": "Roka",
    "lname": "Kamal",
    "email": "roaa223359@bue.edu.eg",
    "phone": "+201558492335",
    "password": "3880",
    "dob": "2003-12-07"
}

